[package]
name = "model-context-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
async-trait = "0.1.83"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
